# version: "3.8"
# services:
#   db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: example
#       POSTGRES_DB: dev-stream
#     volumes:
#       - ./data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dev-stream
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
